### ISSUE TITLE
The graphic on the main page shows polymc

### ISSUE THREAD

**Issue by tomasz-brak** [PrismLauncher/prismlauncher.github.io#16]
![Screenshot_45](https://user-images.githubusercontent.com/62989490/196548953-ec44a486-5e4e-4ca9-ae0e-89453776fc9f.png)

**Comment by MrMelon54** [comment]
Well the rebranded launcher hasn't got any releases yet... once those are our I'm sure someone will update the website

**Comment by Lgmrszd** [comment]
The moment official release drops I'm remaking & submitting PR with new screenshots :smile: 
![image](https://user-images.githubusercontent.com/16291541/196563988-b2be73de-2210-4a2f-a410-932e679f9386.png)

**Comment by MrMelon54** [comment]
you used all the same instances, looks perfect

**Comment by Steveplays28** [comment]
Just wanted to say that the favicon is also still from PolyMC!

**Comment by ZekeSmith** [comment]
screenshots have been changed
