### ISSUE TITLE
"Installing Prism Launcher" Instructions in the Wiki are completely dependent on the non-existent Downloads page

### ISSUE THREAD

**Issue by EvilsSouls** [PrismLauncher/prismlauncher.github.io#29]
Affected File: src/wiki/getting-started/installing-prismlauncher.md

**Comment by jschenke488** [comment]
Downloads page is going to be re-added soon as far as I know. It was removed because there were not any downloads ready.

**Comment by ZekeSmith** [comment]
Download page now exists
